In [1]:
import torch
import torch.nn.functional as F
from torch.distributions import MultivariateNormal as MVN

/Users/yangxinyuxie/miniforge3/envs/GNN/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [88]:
pred = torch.tensor([[[1.,2],[3,4],[2,4],[3,2]],[[1.,2],[3,4],[2,4],[3,2]], [[1.,2],[3,4],[2,4],[3,2]]])
target = torch.tensor([[[1,2],[1,1],[2,7],[0,2]], [[1.,2],[3,4],[2,4],[3,2]], [[1.,2],[3,4],[2,4],[3,2]]])
pred = pred.swapaxes(0,1)
target = target.swapaxes(0,1)
noise_var = 1.0
logits = -(pred.unsqueeze(2) - target.unsqueeze(1))
logits

tensor([[[[-0., -0.],
          [-0., -0.],
          [-0., -0.]],

         [[-0., -0.],
          [-0., -0.],
          [-0., -0.]],

         [[-0., -0.],
          [-0., -0.],
          [-0., -0.]]],


        [[[-2., -3.],
          [-0., -0.],
          [-0., -0.]],

         [[-2., -3.],
          [-0., -0.],
          [-0., -0.]],

         [[-2., -3.],
          [-0., -0.],
          [-0., -0.]]],


        [[[-0.,  3.],
          [-0., -0.],
          [-0., -0.]],

         [[-0.,  3.],
          [-0., -0.],
          [-0., -0.]],

         [[-0.,  3.],
          [-0., -0.],
          [-0., -0.]]],


        [[[-3., -0.],
          [-0., -0.],
          [-0., -0.]],

         [[-3., -0.],
          [-0., -0.],
          [-0., -0.]],

         [[-3., -0.],
          [-0., -0.],
          [-0., -0.]]]])

In [63]:
pred.shape

torch.Size([2, 4, 2])

In [61]:
F.cross_entropy(logits, torch.arange(pred.shape[0]))

tensor(2.2775)

In [86]:
pred = pred[mask].unsqueeze(1)
target = target[mask].unsqueeze(1)

In [87]:
noise_var = 2
logits = - (pred - target.T).pow(2) / (2 * noise_var)

In [88]:
logits

tensor([[ -2.2500,  -4.0000, -16.0000,  -0.2500,   0.0000],
        [ -1.0000,  -2.2500, -12.2500,   0.0000,  -0.2500],
        [ -0.2500,  -1.0000,  -9.0000,  -0.2500,  -1.0000],
        [  0.0000,  -0.2500,  -6.2500,  -1.0000,  -2.2500],
        [ -1.0000,  -0.2500,  -2.2500,  -4.0000,  -6.2500]])

In [83]:
F.cross_entropy(logits, torch.arange(pred.shape[0]))

tensor(4.8177)

In [46]:
F.cross_entropy(logits, torch.arange(pred.shape[0]), reduction='none')

tensor([ 3.6389,  3.5798, 11.5660,  1.9505,  1.7918,  7.6116])

5.669359999999999

In [12]:
F.cross_entropy(logits, torch.arange(5), reduction='none')

tensor([0.3998, 0.9585, 1.9221, 0.9802, 4.7808])

In [7]:
logits = - (pred - target).pow(2) / (2 * noise_var)
-torch.log(torch.exp(logits)/sum(torch.exp(logits)))

tensor([[0.8200],
        [1.0700],
        [1.8200],
        [3.0700],
        [4.8200]])