In [89]:
import torch
import torch.nn.functional as F

In [93]:
torch.isnan(torch.tensor([1])).item() == False

True

In [31]:
pred = torch.tensor([[1,2],[3,4],[5,6]])
target = torch.tensor([[4,5],[9,2],[0,1]])

In [85]:
pred = pred.reshape(-1)
target = target.reshape(-1)
mask = (target!=0)


In [86]:
pred = pred[mask].unsqueeze(1)
target = target[mask].unsqueeze(1)

In [87]:
noise_var = 2
logits = - (pred - target.T).pow(2) / (2 * noise_var)

In [88]:
logits

tensor([[ -2.2500,  -4.0000, -16.0000,  -0.2500,   0.0000],
        [ -1.0000,  -2.2500, -12.2500,   0.0000,  -0.2500],
        [ -0.2500,  -1.0000,  -9.0000,  -0.2500,  -1.0000],
        [  0.0000,  -0.2500,  -6.2500,  -1.0000,  -2.2500],
        [ -1.0000,  -0.2500,  -2.2500,  -4.0000,  -6.2500]])

In [83]:
F.cross_entropy(logits, torch.arange(pred.shape[0]))

tensor(4.8177)

In [46]:
F.cross_entropy(logits, torch.arange(pred.shape[0]), reduction='none')

tensor([ 3.6389,  3.5798, 11.5660,  1.9505,  1.7918,  7.6116])

5.669359999999999

In [12]:
F.cross_entropy(logits, torch.arange(5), reduction='none')

tensor([0.3998, 0.9585, 1.9221, 0.9802, 4.7808])

In [7]:
logits = - (pred - target).pow(2) / (2 * noise_var)
-torch.log(torch.exp(logits)/sum(torch.exp(logits)))

tensor([[0.8200],
        [1.0700],
        [1.8200],
        [3.0700],
        [4.8200]])